version: '3'
services:
  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inside_task
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - "./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql"
  app:
    image: inside_task
    build: .
    ports:
      - 3000:3000
    environment:
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/inside_task?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb